# TODO clp: turn the other actions into docker image since its re downloading packages
# TODO clp: figure out how to have the docs and bins build at on master but not when the release is made
# It could be that its manually ran in this action and then taged and when the changes made here are merged in the actions run again
# This is a waste of build minutes but wouldnt hurt anything 
# Could change the other actions to be on pull requests and nightly and manually? 

name: Create a Release

on:
  workflow_dispatch:
    inputs:
      MAJOR:
        type: string
        description: "The major version for the release"
      MINOR:
        type: string
        description: "The minor version for the release"
      PATCH:
        type: string
        description: "The patch version for the release"

env:
  REPO: ${{github.event.repository.name}}
  MAJOR: ${{ github.event.inputs.MAJOR}}
  MINOR: ${{ github.event.inputs.MINOR}}
  PATCH: ${{ github.event.inputs.PATCH}}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: "master"
          path: ${{env.REPO}}

      - name: Update Version file
        run: |
          cd ${{env.REPO}}
          ./deployment-scripts/deploy.sh
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        # Run latex build
        # Run gcc build
        # Run MSVC build
        # Commit changes as "Relase commit"
        # Tag
        # Release is left to be manual since user will want to fill out 
        # all information they want


  Docs:
    needs: Release
    uses: ./.github/workflows/latex.yml